In [1]:

import pandas as pd
from scipy.io import arff
from sklearn.model_selection import StratifiedKFold
from random import seed
from random import randrange

In [160]:
df = pd.read_excel("Absenteeism_at_work.xls")
df = df.rename(columns={'Son': 'Children'});
df['Absenteeism time in hours'] = df['Absenteeism time in hours'].astype(float)
df['Absenteeism time in hours']
df['Absenteeism time in hours'] = pd.cut(df['Absenteeism time in hours'], [-float("inf"),1.5,2.5,3.5,7.5,12,float("inf")], labels=['a','b','c','d','e','f'])
#df = df['Absenteeism time in hours'].replace(df['Absenteeism time in hours']<float(1.5), 1)
#df = df['Absenteeism time in hours'].replace(df['Absenteeism time in hours'].between(float(1.5), float(2.5)), 2)
#df = df['Absenteeism time in hours'].replace(df['Absenteeism time in hours'].between(2.5, 3.5), 3)
#df = df['Absenteeism time in hours'].replace(df['Absenteeism time in hours'].between(3.5, 7.5), 4)
#df = df['Absenteeism time in hours'].replace(df['Absenteeism time in hours'].between(7.5, 12), 5)
#df = df['Absenteeism time in hours'].replace(df['Absenteeism time in hours']>12, 6)

In [ ]:
list(df.columns.values).drop()

In [161]:
df.head()

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Children,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,239554,...,0,1,2,1,0,1,90,172,30,d
1,36,0,7,3,1,118,13,18,50,239554,...,1,1,1,1,0,0,98,178,31,a
2,3,23,7,4,1,179,51,18,38,239554,...,0,1,0,1,0,0,89,170,31,b
3,7,7,7,5,1,279,5,14,39,239554,...,0,1,2,1,1,0,68,168,24,d
4,11,23,7,5,1,289,36,13,33,239554,...,0,1,2,1,0,1,90,172,30,b

SyntaxError: invalid syntax (<ipython-input-156-6352151f09ba>, line 1)

In [86]:
train_index = df.sample(int(len(df) * 0.8)).index.values
test_index = df.drop(train_index).index.values
prediction = df['Absenteeism time in hours'][train_index].mode()[0]
count = len(df['Absenteeism time in hours'][test_index][df['Absenteeism time in hours'][test_index] == prediction])
accuracy = count/len(df['Absenteeism time in hours'][test_index])
print(prediction, accuracy)

(7.5, 12.0] 0.3108108108108108

In [99]:
def zero_rule_algorithm_classification(df, target):
    predictions = []
    accuracies = []
    for i in range(1,10):
        
        train = df.sample(int(len(df) * 0.8)).index.values
        test= df.drop(train).index.values
        prediction = df[target][train].mode()[0]
        count = len(df[target][test][df[target][test] == prediction])
        accuracy = count/len(df[target][test])
        
        predictions.append(prediction)
        accuracies.append(accuracy)
        
    return predictions, accuracies, max(set(predictions), key=predictions.count), sum(accuracies)/len(accuracies)

print(zero_rule_algorithm_classification(df, 'Absenteeism time in hours'))

([Interval(7.5, 12.0, closed='right'), Interval(7.5, 12.0, closed='right'), Interval(7.5, 12.0, closed='right'), Interval(7.5, 12.0, closed='right'), Interval(7.5, 12.0, closed='right'), Interval(7.5, 12.0, closed='right'), Interval(7.5, 12.0, closed='right'), Interval(7.5, 12.0, closed='right'), Interval(7.5, 12.0, closed='right')], [0.19594594594594594, 0.25, 0.2702702702702703, 0.2972972972972973, 0.2635135135135135, 0.2702702702702703, 0.2702702702702703, 0.25675675675675674, 0.25], Interval(7.5, 12.0, closed='right'), 0.2582582582582582)

In [48]:
def one_rule_algorithm_classification(df, target):

[0, 0, 0]

In [51]:
df['Absenteeism time in hours'].mode()[0]

Interval(7.5, 12.0, closed='right')

In [ ]:
class OneRNominal(object):
    
    def __init__(self):
        self.ideal_variable = None
        self.max_accuracy = 0
    
    def fit(self, X, y):
        response = list()
        result = dict()
        
        dfx = pd.DataFrame(X)
        
        for i in dfx:
            result[str(i)] = dict()
            options_values = set(dfx[i])
            join_data = pd.DataFrame({"variable":dfx[i], "label":y})
            cross_table = pd.crosstab(join_data.variable, join_data.label)
            summary = cross_table.idxmax(axis=1)
            result[str(i)] = dict(summary)
            
            counts = 0
            
            for idx, row in join_data.iterrows():
                if row['label'] == result[str(i)][row['variable']]:
                    counts += 1

            accuracy = (counts/len(y))
            
            if accuracy > self.max_accuracy:
                self.max_accuracy = accuracy
                self.ideal_variable = i

            result_feature = {"variable": str(i), "accuracy":accuracy, "rules": result[str(i)] }  
            response.append(result_feature)
            
        return response

    
    def predict(self, X=None):
        self_ideal_variable = self.ideal_variable + 1
        
    def __repr__(self):
        if self.ideal_variable != None:
            txt = "La mejor variable para tus datos es: " + str(self.ideal_variable)
        else:
            txt = "La mejor variable aun no se ha encontrado, intente ejecutar el metodo fit previamente"
        return txt

In [144]:
unique_classes = pd.unique(df['Reason for absence'])
correct_count = 0
for i in unique_classes.data:
    index = df['Reason for absence'][df['Reason for absence'] == i].index.values
    majority = df['Absenteeism time in hours'][index].mode()[0]
    correct_count += len(df['Absenteeism time in hours'][index][df['Absenteeism time in hours'][index] == majority])
    
correct_count

377

In [192]:
def one_rule_nominal(df, independent, target):
    unique_classes = pd.unique(df[independent])
    correct_count = 0
    for i in unique_classes:
        index = df[independent][df[independent] == i].index.values
        majority = df[target][index].mode()[0]
        correct_count += len(df[target][index][df[target][index] == majority])
    return correct_count;

def one_rule_numeric(df, independent, target):

In [ ]:
def one_r(df, target, nominal, numeric):
    correct_counts={};
    accuracies={}
    for independent in nominal:
        correct_count = one_rule_nominal(df, independent, target)
        correct_counts[independent] = correct_count
        accuracies[independent] = correct_count/len(df)
    for independent in numeric:
        correct_count = one_rule_numeric(df, independent, target)
        correct_counts[independent] = correct_count
        accuracies[independent] = correct_count/len(df)

In [187]:
independents = df.columns.values.tolist()
independents.remove('Absenteeism time in hours')

In [193]:
one_rule_nominal(df,'Reason for absence','Absenteeism time in hours')

377

{'zhang': 1}

In [203]:
from sklearn import tree
import numpy as np
X = df['Reason for absence']
X = np.reshape(X, (-1, 1))
Y = df['Absenteeism time in hours']
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

F:\Anaconda\lib\site-packages\numpy\core\fromnumeric.py:57: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  return getattr(obj, method)(*args, **kwds)

ValueError: Unknown label type: 'unknown'

In [250]:
oneR_df = df[['Distance from Residence to Work','Absenteeism time in hours']]

In [265]:
oneR_df = oneR_df.sort_values('Distance from Residence to Work')
oneR_df.index = range(len(oneR_df))
oneR_df

     Distance from Residence to Work Absenteeism time in hours
0                                  5                         a
1                                  5                         e
2                                  5                         d
3                                  5                         a
4                                  5                         b
5                                  5                         f
6                                 10                         e
7                                 10                         b
8                                 10                         f
9                                 10                         c
10                                10                         b
11                                10                         c
12                                10                         b
13                                10                         f
14                                10                         b
15                                10                         b
16                                10                         a
17                                10                         c
18                                10                         b
19                                10                         e
20                                10                         a
21                                10                         b
22                                10                         a
23                                10                         a
24                                10                         b
25                                10                         d
26                                10                         e
27                                10                         b
28                                10                         e
29                                10                         e
..                               ...                       ...
710                               51                         b
711                               51                         b
712                               51                         b
713                               51                         e
714                               51                         e
715                               51                         c
716                               52                         f
717                               52                         a
718                               52                         e
719                               52                         e
720                               52                         e
721                               52                         e
722                               52                         e
723                               52                         d
724                               52                         e
725                               52                         e
726                               52                         e
727                               52                         e
728                               52                         e
729                               52                         b
730                               52                         e
731                               52                         e
732                               52                         a
733                               52                         a
734                               52                         e
735                               52                         e
736                               52                         e
737                               52                         e
738                               52                         b
739                               52                         d

[740 rows x 2 columns]

In [167]:
import scipy.stats as stats
import math

In [166]:
entropy = stats.entropy(df['Absenteeism time in hours'])
entropy

TypeError: can't multiply sequence by non-int of type 'float'

In [303]:
splitPoint = calculate_split_point(oneR_df, 'Distance from Residence to Work','Absenteeism time in hours' ,pd.unique(df['Absenteeism time in hours']))

In [302]:
def calculate_split_point(df, independent, target, unique):
    splitpoints=[]
    
    if(len(df) < 2):
        return splitpoints
    df.index = range(len(df))
    info_gain_max = 0
    index = 0
    
    for i in range(1, len(df)-1):
        if df[independent][i] == df[independent][i-1]:
            continue
        curr_info_gain = info_gain(df, target, i, unique)
        if curr_info_gain > info_gain_max:
            info_gain_max = curr_info_gain
            index = i
 
    if index >= len(df) or info_gain_max < 0.01:
        return splitpoints
    
    splitpoints.append(df[independent][index]+0.5)    
    splitpoints.extend(calculate_split_point(df[:index], independent, target, unique))
    splitpoints.extend(calculate_split_point(df[index+1:], independent, target, unique))
    return splitpoints
    
def info_gain(df, target, split_point, unique):
    if(len(df) < 2):
        return 0
    entropy = calculate_entropy(df, target, unique)
    entropy1 = calculate_entropy(df[:split_point], target, unique)
    entropy2 = calculate_entropy(df[split_point:], target, unique)
    
    infogain = entropy - (split_point/len(df)) * entropy1 - ((len(df)-split_point)/len(df)) * entropy2
    return infogain

def calculate_entropy(df, target, unique):
    entropy = 0.0
    for i in unique:
        if len(df) == 0:
            continue
        ratio = len(df[df[target] == i])/len(df)
        if ratio == 0:
            continue
        entropy += -1 * ratio * math.log(ratio)
    return entropy

In [225]:
info_gain(df, 'Absenteeism time in hours', 1, pd.unique(df['Absenteeism time in hours']))

0.0032349402069968836

In [123]:
df[df['Transportation expense'] < 200].reset_index()

,index,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,...,Disciplinary failure,Education,Children,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,1,36,0,7,3,1,118,13,18,50,...,1,1,1,1,0,0,98,178,31,"(-inf, 1.5]"
1,2,3,23,7,4,1,179,51,18,38,...,0,1,0,1,0,0,89,170,31,"(1.5, 2.5]"
2,5,3,23,7,6,1,179,51,18,38,...,0,1,0,1,0,0,89,170,31,"(1.5, 2.5]"
3,8,14,19,7,2,1,155,12,14,34,...,0,1,2,1,0,0,95,196,25,"(12.0, inf]"
4,13,3,11,7,4,1,179,51,18,38,...,0,1,0,1,0,0,89,170,31,"(-inf, 1.5]"
5,14,3,23,7,4,1,179,51,18,38,...,0,1,0,1,0,0,89,170,31,"(3.5, 7.5]"
6,16,3,23,7,6,1,179,51,18,38,...,0,1,0,1,0,0,89,170,31,"(1.5, 2.5]"
7,17,3,21,7,2,1,179,51,18,38,...,0,1,0,1,0,0,89,170,31,"(7.5, 12.0]"
8,18,6,11,7,5,1,189,29,13,33,...,0,1,2,0,0,2,69,167,25,"(7.5, 12.0]"
9,21,3,11,8,2,1,179,51,18,38,...,0,1,0,1,0,0,89,170,31,"(-inf, 1.5]"
10,27,30,28,8,4,1,157,27,6,29,...,0,1,0,1,1,0,75,185,22,"(3.5, 7.5]"
11,29,3,23,8,6,1,179,51,18,38,...,0,1,0,1,0,0,89,170,31,"(1.5, 2.5]"
12,30,3,18,8,2,1,179,51,18,38,...,0,1,0,1,0,0,89,170,31,"(7.5, 12.0]"
13,34,3,23,8,2,1,179,51,18,38,...,0,1,0,1,0,0,89,170,31,"(1.5, 2.5]"
14,40,27,23,9,3,1,184,42,7,27,...,0,1,0,0,0,0,58,167,21,"(1.5, 2.5]"
15,41,34,23,9,2,1,118,10,10,37,...,0,1,0,0,0,0,83,172,28,"(3.5, 7.5]"
16,42,3,23,9,3,1,179,51,18,38,...,0,1,0,1,0,0,89,170,31,"(3.5, 7.5]"
17,44,14,23,9,4,1,155,12,14,34,...,0,1,2,1,0,0,95,196,25,"(1.5, 2.5]"
18,45,34,23,9,2,1,118,10,10,37,...,0,1,0,0,0,0,83,172,28,"(2.5, 3.5]"
19,46,3,23,9,3,1,179,51,18,38,...,0,1,0,1,0,0,89,170,31,"(2.5, 3.5]"
20,53,34,23,9,3,4,118,10,10,37,...,0,1,0,0,0,0,83,172,28,"(1.5, 2.5]"
21,55,36,0,9,3,4,118,13,18,50,...,1,1,1,1,0,0,98,178,31,"(-inf, 1.5]"
22,57,3,23,9,4,4,179,51,18,38,...,0,1,0,1,0,0,89,170,31,"(2.5, 3.5]"
23,60,3,23,9,6,4,179,51,18,38,...,0,1,0,1,0,0,89,170,31,"(2.5, 3.5]"
24,62,3,23,10,3,4,179,51,18,38,...,0,1,0,1,0,0,89,170,31,"(2.5, 3.5]"
25,63,34,23,10,3,4,118,10,10,37,...,0,1,0,0,0,0,83,172,28,"(2.5, 3.5]"
26,64,36,0,10,4,4,118,13,18,50,...,1,1,1,1,0,0,98,178,31,"(-inf, 1.5]"
27,65,22,23,10,5,4,179,26,9,30,...,0,3,0,0,0,0,56,171,19,"(-inf, 1.5]"
28,66,3,23,10,6,4,179,51,18,38,...,0,1,0,1,0,0,89,170,31,"(2.5, 3.5]"
29,68,34,23,10,3,4,118,10,10,37,...,0,1,0,0,0,0,83,172,28,"(2.5, 3.5]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,684,22,27,5,6,3,179,26,9,30,...,0,3,0,0,0,0,56,171,19,"(1.5, 2.5]"
294,685,36,23,5,2,3,118,13,18,50,...,0,1,1,1,0,0,98,178,31,"(1.5, 2.5]"
295,686,36,5,5,3,3,118,13,18,50,...,0,1,1,1,0,0,98,178,31,"(2.5, 3.5]"
296,687,34,28,5,3,3,118,10,10,37,...,0,1,0,0,0,0,83,172,28,"(-inf, 1.5]"
297,688,36,0,5,3,3,118,13,18,50,...,1,1,1,1,0,0,98,178,31,"(-inf, 1.5]"
298,689,22,27,5,4,3,179,26,9,30,...,0,3,0,0,0,0,56,171,19,"(1.5, 2.5]"
299,691,17,16,5,6,3,179,22,17,40,...,0,2,2,0,1,0,63,170,22,"(-inf, 1.5]"
300,692,14,10,5,2,3,155,12,14,34,...,0,1,2,1,0,0,95,196,25,"(12.0, inf]"
301,695,17,10,5,4,3,179,22,17,40,...,0,2,2,0,1,0,63,170,22,"(7.5, 12.0]"
302,700,22,27,5,6,3,179,26,9,30,...,0,3,0,0,0,0,56,171,19,"(1.5, 2.5]"
303,702,14,23,5,4,3,155,12,14,34,...,0,1,2,1,0,0,95,196,25,"(1.5, 2.5]"
304,703,17,25,5,6,3,179,22,17,40,...,0,2,2,0,1,0,63,170,22,"(7.5, 12.0]"
305,704,14,10,5,6,3,155,12,14,34,...,0,1,2,1,0,0,95,196,25,"(7.5, 12.0]"
306,706,16,7,6,4,3,118,15,24,46,...,0,1,2,1,1,0,75,175,25,"(7.5, 12.0]"
307,707,22,27,6,4,3,179,26,9,30,...,0,3,0,0,0,0,56,171,19,"(2.5, 3.5]"
308,708,34,26,6,6,3,118,10,10,37,...,0,1,0,0,0,0,83,172,28,"(7.5, 12.0]"
309,709,34,10,6,4,3,118,10,10,37,...,0,1,0,0,0,0,83,172,28,"(7.5, 12.0]"
310,711,36,19,6,5,3,118,13,18,50,...,0,1,1,1,0,0,98,178,31,"(12.0, inf]"
311,713,22,27,6,6,3,179,26,9,30,...,0,3,0,0,0,0,56,171,19,"(1.5, 2.5]"
312,716,36,19,6,5,3,118,13,18,50,...,0,1,1,1,0,0,98,178,31,"(2.5, 3.5]"
313,717,22,13,6,5,3,179,26,9,30,...,0,3,0,0,0,0,56,171,19,"(1.5, 2.5]"
314,719,22,13,6,2,1,179,26,9,30,...,0,3,0,0,0,0,56,171,19,"(2.5, 3.5]"
315,720,34,25,6,2,1,118,10,10,37,...,0,1,0,0,0,0,83,172,28,"(2.5, 3.5]"
316,722,34,8,6,6,1,118,10,10,37,...,0,1,0,0,0,0,83,172,28,"(1.5, 2.5]"
317,723,34,10,6,4,1,118,10,10,37,...,0,1,0,0,0,0,83,172,28,"(2.5, 3.5]"
318,728,34,28,7,2,1,118,10,10,37,...,0,1,0,0,0,0,83,172,28,"(3.5, 7.5]"
319,730,6,22,7,3,1,189,29,13,33,...,0,1,2,0,0,2,69,167,25,"(12.0, inf]"
320,731,34,23,7,4,1,118,10,10,37,...,0,1,0,0,0,0,83,172,28,"(1.5, 2.5]"
321,737,4,0,0,3,1,118,14,13,40,...,0,1,1,1,0,8,98,170,34,"(-inf, 1.5]"
322,739,35,0,0,6,3,179,45,14,53,...,0,1,1,0,0,1,77,175,25,"(-inf, 1.5]"

In [304]:
splitPoint

[50.5,
 36.5,
 26.5,
 14.5,
 13.5,
 12.5,
 11.5,
 10.5,
 22.5,
 20.5,
 17.5,
 15.5,
 16.5,
 25.5,
 29.5,
 27.5,
 31.5,
 35.5,
 42.5,
 49.5,
 45.5,
 52.5,
 51.5]

In [288]:
A = [1,2,3,4,5]
A[1:]

[2, 3, 4, 5]